# Generated by Django 4.0.5 on 2023-05-31 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('contact', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('csv_file', models.FileField(upload_to='')),
                ('email', models.EmailField(max_length=254)),
                ('country', models.CharField(max_length=100)),
                ('industry', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Active Leads', 'Active'), ('Dead Leads', 'Dead')], default='Active Leads', max_length=50)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'leads',
                'db_table': 'leads_leads',
            },
        ),
    ]
